### ISSUE TITLE
Evidenziare monumenti di qualità

### ISSUE THREAD

**Issue by DarioYiyi** [ferdi2005/monumenti#14]
Sarebbe molto utile evidenziare in colore oro (`#ffd700`) i monumenti che hanno almeno una fotografia di qualità, affinché ci si possa eventualmente concentrare su altri monumenti.
     Definizione di fotografia di qualità: il file deve avere almeno una di queste due categorie:
     - https://commons.wikimedia.org/wiki/Category:Quality_images
     - https://commons.wikimedia.org/wiki/Category:Featured_pictures_on_Wikimedia_Commons

**Comment by ferdi2005** [comment]
A titolo statistico, ci sono 159 monumenti di qualità o featured, di cui 158 monumenti di qualità, 7 featured, 6 sia di qualità sia featured
